/**
 * Pre-built Model Canvas Architectures & Templates for Vision Platform.
 * Each template includes ReactFlow nodes & edges ready for live canvas rendering,
 * code generation, and 1-click training configuration.
 */

export const MODEL_TEMPLATES = [
  {
    id: 'iris_classifier',
    name: 'Iris 3-Class Dense Classifier',
    category: 'Classification',
    badge: 'Multi-Class (3 classes)',
    color: 'cyan',
    description: 'Compact feed-forward neural network for classifying Iris flowers into Setosa, Versicolor, or Virginica.',
    recommendedDataset: 'iris_classification.csv',
    recommendedDatasetId: 'iris_classification',
    recommendedTarget: 'species_id',
    problem_type_id: 1,
    optimizer: 'adam',
    metric: 'accuracy',
    epochs: 20,
    batch_size: 16,
    inputShape: '(4,)',
    outputShape: '(3,)',
    nodes: [
      {
        id: 'node-1',
        type: 'input',
        position: { x: 280, y: 40 },
        data: { label: 'Input (4 features)', params: { 'dim-1': '4', 'dim-2': '', 'dim-3': '' } },
      },
      {
        id: 'node-2',
        type: 'dense',
        position: { x: 280, y: 150 },
        data: { label: 'Dense (32, ReLU)', params: { units: 32, activation: 'relu' } },
      },
      {
        id: 'node-3',
        type: 'dropout',
        position: { x: 280, y: 260 },
        data: { label: 'Dropout (0.2)', params: { rate: 0.2 } },
      },
      {
        id: 'node-4',
        type: 'dense',
        position: { x: 280, y: 370 },
        data: { label: 'Dense (16, ReLU)', params: { units: 16, activation: 'relu' } },
      },
      {
        id: 'node-5',
        type: 'dense',
        position: { x: 280, y: 480 },
        data: { label: 'Dense (3, Softmax)', params: { units: 3, activation: 'softmax' } },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2' },
      { id: 'e2-3', source: 'node-2', target: 'node-3' },
      { id: 'e3-4', source: 'node-3', target: 'node-4' },
      { id: 'e4-5', source: 'node-4', target: 'node-5' },
    ],
    layersSummary: ['Input (4)', 'Dense 32 (ReLU)', 'Dropout 0.2', 'Dense 16 (ReLU)', 'Dense 3 (Softmax)'],
    highlights: ['Low computational cost', 'Instant convergence', 'High accuracy on botanical data'],
  },
  {
    id: 'heart_disease_mlp',
    name: 'Heart Disease Clinical Classifier',
    category: 'Healthcare Tabular',
    badge: 'Binary Classification',
    color: 'violet',
    description: 'Deep Multilayer Perceptron with Batch Normalization and Dropout regularization for medical risk prediction.',
    recommendedDataset: 'heart_disease.csv',
    recommendedDatasetId: 'heart_disease',
    recommendedTarget: 'heart_disease',
    problem_type_id: 1,
    optimizer: 'adam',
    metric: 'accuracy',
    epochs: 25,
    batch_size: 32,
    inputShape: '(11,)',
    outputShape: '(2,)',
    nodes: [
      {
        id: 'node-1',
        type: 'input',
        position: { x: 280, y: 40 },
        data: { label: 'Input (11 clinical features)', params: { 'dim-1': '11', 'dim-2': '', 'dim-3': '' } },
      },
      {
        id: 'node-2',
        type: 'batchnorm',
        position: { x: 280, y: 150 },
        data: { label: 'Batch Normalization', params: {} },
      },
      {
        id: 'node-3',
        type: 'dense',
        position: { x: 280, y: 260 },
        data: { label: 'Dense (64, ReLU)', params: { units: 64, activation: 'relu' } },
      },
      {
        id: 'node-4',
        type: 'dropout',
        position: { x: 280, y: 370 },
        data: { label: 'Dropout (0.3)', params: { rate: 0.3 } },
      },
      {
        id: 'node-5',
        type: 'dense',
        position: { x: 280, y: 480 },
        data: { label: 'Dense (32, ReLU)', params: { units: 32, activation: 'relu' } },
      },
      {
        id: 'node-6',
        type: 'dense',
        position: { x: 280, y: 590 },
        data: { label: 'Dense (2, Softmax)', params: { units: 2, activation: 'softmax' } },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2' },
      { id: 'e2-3', source: 'node-2', target: 'node-3' },
      { id: 'e3-4', source: 'node-3', target: 'node-4' },
      { id: 'e4-5', source: 'node-4', target: 'node-5' },
      { id: 'e5-6', source: 'node-5', target: 'node-6' },
    ],
    layersSummary: ['Input (11)', 'BatchNorm', 'Dense 64', 'Dropout 0.3', 'Dense 32', 'Dense 2 (Softmax)'],
    highlights: ['Feature normalization built-in', 'Overfitting prevention with Dropout', 'Excellent for clinical tabular metrics'],
  },
  {
    id: 'customer_churn_mlp',
    name: 'Customer Churn Predictor',
    category: 'Business Analytics',
    badge: 'Binary Classification',
    color: 'amber',
    description: 'Enterprise tabular architecture designed for customer demographics, financial transactions, and churn likelihood.',
    recommendedDataset: 'customer_churn.csv',
    recommendedDatasetId: 'customer_churn',
    recommendedTarget: 'churn',
    problem_type_id: 1,
    optimizer: 'adam',
    metric: 'accuracy',
    epochs: 20,
    batch_size: 32,
    inputShape: '(8,)',
    outputShape: '(2,)',
    nodes: [
      {
        id: 'node-1',
        type: 'input',
        position: { x: 280, y: 40 },
        data: { label: 'Input (8 attributes)', params: { 'dim-1': '8', 'dim-2': '', 'dim-3': '' } },
      },
      {
        id: 'node-2',
        type: 'dense',
        position: { x: 280, y: 150 },
        data: { label: 'Dense (64, ReLU)', params: { units: 64, activation: 'relu' } },
      },
      {
        id: 'node-3',
        type: 'batchnorm',
        position: { x: 280, y: 260 },
        data: { label: 'Batch Normalization', params: {} },
      },
      {
        id: 'node-4',
        type: 'dense',
        position: { x: 280, y: 370 },
        data: { label: 'Dense (32, ReLU)', params: { units: 32, activation: 'relu' } },
      },
      {
        id: 'node-5',
        type: 'dropout',
        position: { x: 280, y: 480 },
        data: { label: 'Dropout (0.2)', params: { rate: 0.2 } },
      },
      {
        id: 'node-6',
        type: 'dense',
        position: { x: 280, y: 590 },
        data: { label: 'Dense (2, Softmax)', params: { units: 2, activation: 'softmax' } },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2' },
      { id: 'e2-3', source: 'node-2', target: 'node-3' },
      { id: 'e3-4', source: 'node-3', target: 'node-4' },
      { id: 'e4-5', source: 'node-4', target: 'node-5' },
      { id: 'e5-6', source: 'node-5', target: 'node-6' },
    ],
    layersSummary: ['Input (8)', 'Dense 64', 'BatchNorm', 'Dense 32', 'Dropout 0.2', 'Dense 2 (Softmax)'],
    highlights: ['Scales well to large customer tables', 'High precision on churn patterns', 'Fast training'],
  },
  {
    id: 'housing_price_regressor',
    name: 'Deep Real Estate Price Regressor',
    category: 'Regression',
    badge: 'Continuous Prediction',
    color: 'emerald',
    description: 'Multi-layer deep regression network for predicting continuous numerical variables like median housing prices.',
    recommendedDataset: 'california_housing.csv',
    recommendedDatasetId: 'california_housing',
    recommendedTarget: 'median_house_value',
    problem_type_id: 2,
    optimizer: 'adam',
    metric: 'mse',
    epochs: 30,
    batch_size: 32,
    inputShape: '(8,)',
    outputShape: '(1,)',
    nodes: [
      {
        id: 'node-1',
        type: 'input',
        position: { x: 280, y: 40 },
        data: { label: 'Input (8 geographic & census cols)', params: { 'dim-1': '8', 'dim-2': '', 'dim-3': '' } },
      },
      {
        id: 'node-2',
        type: 'dense',
        position: { x: 280, y: 150 },
        data: { label: 'Dense (128, ReLU)', params: { units: 128, activation: 'relu' } },
      },
      {
        id: 'node-3',
        type: 'dense',
        position: { x: 280, y: 260 },
        data: { label: 'Dense (64, ReLU)', params: { units: 64, activation: 'relu' } },
      },
      {
        id: 'node-4',
        type: 'dense',
        position: { x: 280, y: 370 },
        data: { label: 'Dense (32, ReLU)', params: { units: 32, activation: 'relu' } },
      },
      {
        id: 'node-5',
        type: 'dense',
        position: { x: 280, y: 480 },
        data: { label: 'Dense (1, Linear Output)', params: { units: 1, activation: 'none' } },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2' },
      { id: 'e2-3', source: 'node-2', target: 'node-3' },
      { id: 'e3-4', source: 'node-3', target: 'node-4' },
      { id: 'e4-5', source: 'node-4', target: 'node-5' },
    ],
    layersSummary: ['Input (8)', 'Dense 128 (ReLU)', 'Dense 64 (ReLU)', 'Dense 32 (ReLU)', 'Dense 1 (Linear)'],
    highlights: ['MSE / MAE loss optimization', 'Linear output head for real values', 'Hierarchical feature reduction'],
  },
  {
    id: 'mnist_digit_classifier',
    name: 'MNIST Handwritten Digits (8x8) Net',
    category: 'Computer Vision',
    badge: '10-Class Digit Recognition',
    color: 'pink',
    description: 'Feed-forward optical recognition model mapping 64 pixel features to 10 handwritten digit classes (0–9).',
    recommendedDataset: 'mnist_digits_mini.csv',
    recommendedDatasetId: 'mnist_digits_mini',
    recommendedTarget: 'digit_label',
    problem_type_id: 3,
    optimizer: 'adam',
    metric: 'accuracy',
    epochs: 25,
    batch_size: 32,
    inputShape: '(64,)',
    outputShape: '(10,)',
    nodes: [
      {
        id: 'node-1',
        type: 'input',
        position: { x: 280, y: 40 },
        data: { label: 'Input (64 pixel values)', params: { 'dim-1': '64', 'dim-2': '', 'dim-3': '' } },
      },
      {
        id: 'node-2',
        type: 'dense',
        position: { x: 280, y: 150 },
        data: { label: 'Dense (128, ReLU)', params: { units: 128, activation: 'relu' } },
      },
      {
        id: 'node-3',
        type: 'dropout',
        position: { x: 280, y: 260 },
        data: { label: 'Dropout (0.25)', params: { rate: 0.25 } },
      },
      {
        id: 'node-4',
        type: 'dense',
        position: { x: 280, y: 370 },
        data: { label: 'Dense (64, ReLU)', params: { units: 64, activation: 'relu' } },
      },
      {
        id: 'node-5',
        type: 'dense',
        position: { x: 280, y: 480 },
        data: { label: 'Dense (10, Softmax)', params: { units: 10, activation: 'softmax' } },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2' },
      { id: 'e2-3', source: 'node-2', target: 'node-3' },
      { id: 'e3-4', source: 'node-3', target: 'node-4' },
      { id: 'e4-5', source: 'node-4', target: 'node-5' },
    ],
    layersSummary: ['Input (64)', 'Dense 128 (ReLU)', 'Dropout 0.25', 'Dense 64 (ReLU)', 'Dense 10 (Softmax)'],
    highlights: ['95%+ accuracy on 8x8 digits', 'Handles flattened image grids', 'Fast 10-class softmax distribution'],
  },
  {
    id: 'convnet_2d_vision',
    name: '2D Convolutional Vision Network (ConvNet)',
    category: 'Computer Vision',
    badge: 'CNN 2D Image Feature Extractor',
    color: 'blue',
    description: 'Convolutional neural network featuring Conv2D filters, MaxPooling, and Flatten layers for 2D spatial image grids.',
    recommendedDataset: 'sample_images.zip',
    recommendedDatasetId: 'sample_images',
    recommendedTarget: 'folder_label',
    problem_type_id: 1,
    optimizer: 'adam',
    metric: 'accuracy',
    epochs: 20,
    batch_size: 16,
    inputShape: '(64, 64, 3)',
    outputShape: '(3,)',
    nodes: [
      {
        id: 'node-1',
        type: 'input',
        position: { x: 280, y: 40 },
        data: { label: 'Input Image (64, 64, 3)', params: { 'dim-1': '64', 'dim-2': '64', 'dim-3': '3' } },
      },
      {
        id: 'node-2',
        type: 'conv',
        position: { x: 280, y: 150 },
        data: { label: 'Conv2D (32, 3x3, same)', params: { filters: 32, kernelX: 3, kernelY: 3, strideX: 1, strideY: 1, padding: 'same', activation: 'relu' } },
      },
      {
        id: 'node-3',
        type: 'maxpool',
        position: { x: 280, y: 260 },
        data: { label: 'MaxPool2D (2x2)', params: { poolSize: 2 } },
      },
      {
        id: 'node-4',
        type: 'conv',
        position: { x: 280, y: 370 },
        data: { label: 'Conv2D (64, 3x3, same)', params: { filters: 64, kernelX: 3, kernelY: 3, strideX: 1, strideY: 1, padding: 'same', activation: 'relu' } },
      },
      {
        id: 'node-5',
        type: 'maxpool',
        position: { x: 280, y: 480 },
        data: { label: 'MaxPool2D (2x2)', params: { poolSize: 2 } },
      },
      {
        id: 'node-6',
        type: 'flatten',
        position: { x: 280, y: 590 },
        data: { label: 'Flatten', params: {} },
      },
      {
        id: 'node-7',
        type: 'dense',
        position: { x: 280, y: 700 },
        data: { label: 'Dense (64, ReLU)', params: { units: 64, activation: 'relu' } },
      },
      {
        id: 'node-8',
        type: 'dense',
        position: { x: 280, y: 810 },
        data: { label: 'Dense (3, Softmax)', params: { units: 3, activation: 'softmax' } },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2' },
      { id: 'e2-3', source: 'node-2', target: 'node-3' },
      { id: 'e3-4', source: 'node-3', target: 'node-4' },
      { id: 'e4-5', source: 'node-4', target: 'node-5' },
      { id: 'e5-6', source: 'node-5', target: 'node-6' },
      { id: 'e6-7', source: 'node-6', target: 'node-7' },
      { id: 'e7-8', source: 'node-7', target: 'node-8' },
    ],
    layersSummary: ['Input (64,64,3)', 'Conv2D 32', 'MaxPool 2x2', 'Conv2D 64', 'MaxPool 2x2', 'Flatten', 'Dense 64', 'Dense 3'],
    highlights: ['Spatial 2D convolution filters', 'Downsampling with pooling', 'Standard computer vision pipeline'],
  },
];
